# Generated by Django 5.0.5 on 2024-05-07 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume', models.FloatField()),
                ('category', models.CharField(choices=[('ST', 'Stimulating'), ('RF', 'Refreshing'), ('AL', 'Alcohol'), ('NR', 'Nourishing')], default=None, max_length=2)),
            ],
            options={
                'verbose_name': 'Beverage',
                'verbose_name_plural': 'Beverages',
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('SS', 'Starter'), ('SD', 'Salads'), ('SP', 'Soup'), ('MN', 'Main'), ('SE', 'Side'), ('DS', 'Dessert')], default=None, max_length=2)),
            ],
            options={
                'verbose_name': 'Dish',
                'verbose_name_plural': 'Dishes',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PR', 'In process'), ('DN', 'Done'), ('CN', 'Cancelled')], default=None, max_length=2)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_restik.dish')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_restik.order')),
            ],
        ),
    ]
