# Generated by Django 5.0.5 on 2024-05-11 10:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_restik', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beverage',
            name='category',
            field=models.CharField(choices=[('Stimulating', 'Stimulating'), ('Refreshing', 'Refreshing'), ('Alcohol', 'Alcohol'), ('Nourishing', 'Nourishing')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.CharField(choices=[('Starter', 'Starter'), ('Salads', 'Salads'), ('Soup', 'Soup'), ('Main', 'Main'), ('Side', 'Side'), ('Dessert', 'Dessert')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('In process', 'In process'), ('Done', 'Done'), ('Cancelled', 'Cancelled')], default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='ordereditem',
            name='quantity',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
